default:
  site_name: 'Public'
  welcome_message: "Welcome to Annotation Studio 2.5"
  site_color: '#CCC'
  brand: 'shared/default_brand'
public:
  site_name: 'Public'
  welcome_message: "Welcome to Annotation Studio 2.5"
  site_color: '#CCC'
amherst:
  site_name: 'Amherst'
  welcome_message: "Welcome to Annotation Studio 2.5"
  site_color: '#2C0463'
andersen:
  site_name: 'Andersen'
  welcome_message: "Welcome to Annotation Studio 2.5"
  site_color: '#997F3D'
barnard:
  site_name: 'Barnard College'
  welcome_message: "Welcome to Annotation Studio 2.5 at <strong>Barnard College</strong>"
  site_color: '#005596'
breck:
  site_name: 'Breck'
  welcome_message: "Welcome to Annotation Studio 2.5"
  site_color: '#000080'
bucknell:
  site_name: 'Bucknell University'
  welcome_message: "Welcome to Annotation Studio 2.5 at <strong>Bucknell University</strong>"
  site_color: '#00337F'
demo:
  site_name: 'Demo'
  welcome_message: "Welcome to Annotation Studio 2.5"
  site_color: '#BDBDBD'
gatech:
  site_name: 'Georgia Tech'
  welcome_message: "Welcome to Annotation Studio 2.5"
  site_color: '#B3A369'
grinnell:
  site_name: 'Grinnell College'
  welcome_message: "Welcome to Annotation Studio 2.5"
  site_color: '#DA291C'
harvard:
  site_name: 'Harvard'
  welcome_message: "Welcome to Annotation Studio 2.5"
  site_color: '#A51C30'
humboldt:
  site_name: 'HU Berlin'
  welcome_message: "Welcome to Annotation Studio 2.5"
  site_color: '#010963'
merchant-of-venice:
  site_name: 'Merchant of Venice'
  welcome_message: "Welcome to Annotation Studio 2.5"
  site_color: '#D2B48C'
mit:
  site_name: 'MIT'
  welcome_message: "Welcome to Annotation Studio 2.5 at <strong>MIT</strong>"
  site_color: '#A31F34'
  brand: 'shared/default_brand'
newhaven:
  site_name: 'University of New Haven'
  welcome_message: "Welcome to Annotation Studio 2.5 at <strong>University of New Haven</strong>"
  site_color: '#FFD700'
stonybrook:
  site_name: 'Stony Brook'
  welcome_message: "Welcome to Annotation Studio 2.5 at <strong>Stony Brook University</strong>"
  site_color: '#990000'
uma:
  site_name: 'UMass Amherst'
  welcome_message: "Welcome to Annotation Studio 2.5 <strong>University of Massachusetts, Amherst</strong>"
  site_color: '#881c1c'
umb:
  site_name: 'UMass Boston'
  welcome_message: "Welcome to Annotation Studio 2.5 at <strong>University of Massachusetts, Boston</strong>"
  site_color: '#38197A'
uw:
  site_name: 'University of Washington'
  welcome_message: "Welcome to Annotation Studio 2.5 at <strong>University of Washington</strong>"
  site_color: '#B7A57A'
vassar:
  site_name: 'Vassar'
  welcome_message: "Welcome to Annotation Studio 2.5 at <strong>Vassar College</strong>"
  site_color: '#800000'
washjeff:
  site_name: 'Washington and Jefferson'
  welcome_message: "Welcome to Annotation Studio 2.5 at <strong>Washington and Jefferson College</strong>"
  site_color: '#FF0000'
wellesley:
  site_name: 'Wellesley'
  welcome_message: "Welcome to Annotation Studio 2.5 at <strong>Wellesley College</strong>"
  site_color: '#002776'
wheatoncollege:
  site_name: 'Wheaton College'
  welcome_message: "Welcome to Annotation Studio 2.5 at <strong>Wheaton College</strong>"
  site_color: '#FFA5000'
wit:
  site_name: 'WIT'
  welcome_message: "Welcome to Annotation Studio 2.5 at <strong>Wentworth Institute of Technology</strong>"
  site_color: '#FFD700'
wlu:
  site_name: 'WLU'
  welcome_message: "Welcome to Annotation Studio 2.5 at <strong>Washington and Lee University</strong>"
  site_color: '#F169E1'
